### ISSUE TITLE
AttributeError: module 'black' has no attribute 'get_string_prefix'

### ISSUE THREAD

**Issue by benjaminbluhm** [inspera/blackbricks#13]
Hi,

Closely related to this [issue](https://github.com/inspera/blackbricks/issues/12).

Would need to change `black.get_string_prefix` to `black.strings.get_string_prefix` in line 60 of blackbricks.py

Might be worth checking if any other issues may arise from recent black restructuring. 

Would be great to have this updated as we are using your library quite extensively, great work, thanks!

**Comment by bsamseth** [comment]
Thanks for reporting this! This has now been fixed, and I've taken a few minor steps to try to decrease the likelihood of this type of thing slipping through again in the future. 

Nice to hear you are finding it useful!
