### ISSUE TITLE
Remove empty cells when run format

### ISSUE THREAD

**Issue by PeterFogh** [inspera/blackbricks#42]
Hi, I have a feature request. 

I think that blackbrick should remove empty cells.  Meaning remove cells containing:
- only whitespaces
- only the format magic specification e.g. "MAGIC %sql" or "MAGIC %python" ect.

Empty cells are often added by mistake to the end of a notebook when one just spams Shift+Enter to run all cells indevidually.

I suppose this can be implemeted "simply" in  https://github.com/inspera/blackbricks/blob/6be4e1f95bbf7e2ede4cb16aa96a3934cc5db69a/blackbricks/blackbricks.py#L47-L50 by only append the cell to `output_cells ` if it do not satisfy the conditions stated above.

Looking forward to hear your opinion.

**Comment by bsamseth** [comment]
Hi! I agree this could be useful, as I have now developed the habit of _not_ spamming shift+enter for this very reason. My only reservation is that this could be painful if enabled by default for anyone who have blackbricks running "on save" in their editors. I have had similar issues before with other tools, and in this case it could make it hard to create new cells when editing locally. 

That said, I think a boolean command line flag to enable this feature would be a good addition. It should just be false by default, at least in this major version.

I don't have much capacity to work on blackbricks at the moment, but I will be happy to review a PR if you'd like to add this feature 👍🏻
