### ISSUE TITLE
Discussion: sqlparse vs sqlfluff

### ISSUE THREAD

**Issue by PeterFogh** [inspera/blackbricks#43]
Hi, first of all, thanks for developing blackbricks, and enabling better software practices for notebooks 😄 

I have been interested in Python code formatting packages for the last couple of years and have used some in different small projects.

Currently, I'm developing a "data platform" for my company which mainly builds on top of Databricks. As part of this platform, I implemented pre-commit and CI validation of our code formats, including Python and SQL script and in Databricks notebooks.

After investigating the area of different open-source SQL formatters, I decided to use [sqlfluff](https://github.com/sqlfluff/sqlfluff/) for my company SQL scripts and blackbricks for our Databricks notebooks, which (as you know) uses [sqlparser](https://github.com/andialbrecht/sqlparse).

My question is: Why use sqlparse instead of sqlfluff?

## sqlfluff procs:
1. The community is bigger, as seen by the activity score and stars difference, see a comparison here: https://www.libhunt.com/compare-sqlfluff-vs-sqlparse. A bigger community results in more contributions, and more tests of use cases and edge cases.
2. As sqlfluff covers multiple SQL dialects, thus blackbrick can also better support different dialects, as Databricks often operate different SQL engines.
3. Sqlfluff already has many of the features sqlparser does not have yet, e.g. configuration via config file; https://github.com/inspera/blackbricks/issues/31#issuecomment-1523227971
4. Sqlfluff has better documentation, possibly due to a bigger community.

## sqlfluff cons:
1. As the community and code base is larger than sqlparser, changes can be more complex to add and more time costly.
2. As sqlfluff covers multiple SQL dialects, thus a decision and solution has to be developed to fully "automate" the "Format notebooks" action in databricks notebooks.

## Solution direction?
I think that sqlfluff can be substituted with sqlparser, using it as python package and running `sqlfluff.fix(my_bad_query, dialect="databricks")`, see this example https://github.com/sqlfluff/sqlfluff/blob/a20005a6647dbd7fc4ac228897db5b0d776defa7/examples/01_basic_api_usage.py#L26.
To decide the dialect I see 3 options blackbricks has:

1. assume the dialect always is "databricks", "SparkSQL", or "ANSI". ANSI will probably not provide any errors, but has to be tested.
2. develop some code in sqlfluff or blackbricks that with an heuristic guess the dialect.
3. blackblicks enables the user via a comment in SQL cells and code snippets to specify the dialect. Got inspiration from sqlfluff' inline config, see https://docs.sqlfluff.com/en/stable/configuration.html#in-file-configuration-directives

I'm looking forward to discussing this 😃

**Comment by bsamseth** [comment]
> Hi, first of all, thanks for developing blackbricks, and enabling better software practices for notebooks 😄

You're most welcome!

> My question is: Why use sqlparse instead of sqlfluff?

The short answer: Because blackbricks was born early in 2020, and sqlfluff was pre-alpha at that point (pluss I didn't find it when searching around back then).

What about now? No argument, sqlfluff has a lot of value, but making a change now would likely be non-trivial. Realistically, _I_ won't do the work to change to sqlfluff. This is simply because I hardly every have SQL in my notebooks, sticking to pyspark 99% of the time, so I can't find the motivation to work on this. 

With that said, I'm more than happy to review contributions and even adding contributors if that makes sense. If this is to be done, perhaps a refactoring of blackbricks to be plugin-based, as discussed in #26, could be a way to integrate this and other tools.

**Comment by runkelcorey** [comment]
@PeterFogh any interest in collaborating on refactoring, using SQLFluff as the original instance? I'd like `blackbricks` to call SQLFluff as well
