### ISSUE TITLE
Combine black and blackbricks?

### ISSUE THREAD

**Issue by cm-halfspace** [inspera/blackbricks#47]
Hi, 

I have a large directory with a combination of regular python files and some databricks notebooks. 
Do you have any example of how to run black on the normal python files and blackbricks on the databricks notebooks? 
Would be nice to have a small option in blackbricks to run both :) 

Cheers,

**Comment by bsamseth** [comment]
Blackbricks will ignore any non-notebook file. Black has extensive options for including/ignoring paths. So you have two main options:

1. Separate notebooks from regular files into distinct folders, and configure black to ignore the notebook folder. 
2. Run black on everything first, then run blackbricks on everything. That should have the same net effect. 

Hope that helps!
