### ISSUE TITLE
Format SQL notebooks

### ISSUE THREAD

**Issue by erummel** [inspera/blackbricks#50]
Blackbricks is currently designed to only format Python notebooks (text files with a `# Databricks notebook source` [header](https://github.com/inspera/blackbricks/blob/master/blackbricks/blackbricks.py#L9)). I'd like to implement formatting of SQL notebooks (`-- Databricks notebooks source` header), as well. I will try to write some new tests and will definitely clarify this change in the docs.

What do you think? Does this align with your vision for Blackbricks?

**Comment by bsamseth** [comment]
Sorry for the somewhat late response. 

In short, no, I don't think that belongs in blackbricks. It sounds like a different tool. I somewhat regret adding sql formatting to blackbricks at all, as it was done mostly as an afterthought, and it shows. The focus has always been Python notebook, as the name implies by being tied to `black`.

I'd instead lobby for Databricks to add this to `dbx`. Really, `dbx` should IMO get general formatting/linting of notebooks, and ideally make blackbricks obsolete. If you're going to make an effort and make a significant PR, I'd do it to https://github.com/databrickslabs/dbx 👍🏻
