### ISSUE TITLE
blackbricks expects username and password lines in ~/.databrickscfg

### ISSUE THREAD

**Issue by akbo** [inspera/blackbricks#6]
My ~/.databrickscfg neither has a `username = <something>`, nor a `password = <something>` line. It was created via `databricks configure --token` as described in [the Databricks docs](https://docs.databricks.com/dev-tools/cli/index.html) and only features a `host = <something>` and a `token = <something>` line in the DEFAULT profile.

Apparently blackbricks expects the username and password lines to be present in the .databrickscfg profile as it crashes in their absence when trying to regex match the [username](https://github.com/inspera/blackbricks/blob/master/blackbricks/databricks_sync.py#L82) and the [password](https://github.com/inspera/blackbricks/blob/master/blackbricks/databricks_sync.py#L85).

**Comment by bsamseth** [comment]
@akbo I see, I wasn't aware of that option. Good to know! I'll redo the credential-finding logic as soon as I have the time. If you want it fixed asap I'm happy to accept a PR :+1:

**Comment by akbo** [comment]
Hi @bsamseth, I created the following PR to add token auth: https://github.com/inspera/blackbricks/pull/7

Not sure how I can link it to this issue.

**Comment by bsamseth** [comment]
Thanks! I'll get this reviewed some time today.

As for linking to issues, see e.g.
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
