### ISSUE TITLE
black.InvalidInput: Cannot parse

### ISSUE THREAD

**Issue by tinyweasel** [inspera/blackbricks#9]
I'm trying to format a notebook and it's failing. Could it be because I've used markdown cells?

**Comment by bsamseth** [comment]
Without any other information, I really can't help you. I'd need to see a _minimal_ example notebook that produces your error and/or the full error message, along with the output of 
```
black --version
blackbricks --version
```

Markdown cells should work without issue, they should be fully ignored by blackbricks.
